wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1643654955
    t:
      1:
      - 1
      - 2
      - 3
      3:
      - 13
      - 16
      4: 3.9.7
      5: 0.12.9
      8:
      - 1
      - 3
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 20
bbox_interval:
  desc: null
  value: -1
bcc_epoch:
  desc: null
  value: 0
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: ''
confusion_matrix_diagonal_prior_hyp:
  desc: null
  value: 0.1
convergence_threshold_hyp:
  desc: null
  value: 1.0e-06
data:
  desc: null
  value: ../data/All_Volunteers_Crowdsourced.yaml
data_dict:
  desc: null
  value:
    names:
    - calculus-plaque
    - dental-caries
    - bone-loss
    nc: 3
    path: ../data/datasets
    test: ..\data\datasets\All_Volunteers_Crowdsourced\images\test
    train: ..\data\datasets\All_Volunteers_Crowdsourced\images\train
    val: ..\data\datasets\All_Volunteers_IID\images\val
device:
  desc: null
  value: cpu
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 2
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value: 0
hybrid_conf_thres:
  desc: null
  value: 0.0
hybrid_entropy_thres:
  desc: null
  value: 0.0
hyp:
  desc: null
  value:
    anchor_t: 4.0
    box: 0.05
    cls: 0.5
    cls_pw: 1.0
    copy_paste: 0.0
    degrees: 0.0
    fl_gamma: 0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.015
    hsv_s: 0.7
    hsv_v: 0.4
    iou_t: 0.2
    lr0: 0.01
    lrf: 0.2
    mixup: 0.0
    momentum: 0.937
    mosaic: 1.0
    obj: 1.0
    obj_pw: 1.0
    perspective: 0.0
    scale: 0.5
    shear: 0.0
    translate: 0.1
    warmup_bias_lr: 0.1
    warmup_epochs: 3.0
    warmup_momentum: 0.8
    weight_decay: 0.0005
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 640
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: Expset2_all_cyolo
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
patience:
  desc: null
  value: 1100
project:
  desc: null
  value: runs/train
qt_thres:
  desc: null
  value: 0.0
qt_thres_mode:
  desc: null
  value: ''
qtfilter_epoch:
  desc: null
  value: -1
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs\train\Expset2_all_cyolo92
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5s.pt
workers:
  desc: null
  value: 8
